backend-api:
  replicaCount: 2
  image:
    repository: shiner2/backend-api
    tag: latest
  service:
    type: NodePort
    port: 5000
    nodePort: 30500

frontend:
  replicaCount: 2
  image:
    repository: shiner2/frontend
    tag: latest
  service:
    type: NodePort
    port: 80
    nodePort: 30081
